import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/common/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
/*   title: "Create Next App",
  description: "Generated by create next app", */

  title: "Course Advisor",
  description: "The all-in-one tool for course advising",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
